version: '3.3'
services:
    web:
        build: .
        container_name: "web"
        volumes:
          - ./tmp/db:/var/lib/mongodb/data
        ports:
          - 8000:8000
        links:
          - mongodb
        depends_on:
          - mongodb

    mongodb:
        image: mongo:latest
        container_name: "mongodb"
        volumes:
          - ./data/db:/data/db
        ports:
            - 27018:27018
        command: mongod --smallfiles --logpath=/dev/null
